spring:
  application:
    name: big-event
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      host: localhost
      port: 27017
      database: articledb
  rabbitmq:
    host: localhost
    port: 5672
    username: weihy
    password: 1020
    virtual-host: /

mybatis:
  configuration:
    map-underscore-to-camel-case: true